DROP POLICY IF EXISTS "Allow public read access on oracle_snapshots" ON oracle_snapshots;
DROP POLICY IF EXISTS "Allow public read access on creator_confirmations" ON creator_confirmations;
DROP POLICY IF EXISTS "Allow public read access on creator_profiles" ON creator_profiles;
DROP POLICY IF EXISTS "Allow public read access on market_settlements" ON market_settlements;
DROP POLICY IF EXISTS "Allow public read access on market_resolutions" ON market_resolutions;
DROP POLICY IF EXISTS "Allow public read access on market_events" ON market_events;
DROP POLICY IF EXISTS "Allow public read access on market_positions" ON market_positions;
DROP POLICY IF EXISTS "Allow public read access on markets" ON markets;
DROP POLICY IF EXISTS "Allow public read access on belief_sources" ON belief_sources;
DROP POLICY IF EXISTS "Allow public read access on beliefs" ON beliefs;
DROP POLICY IF EXISTS "Allow public read access on users" ON users;

DROP INDEX IF EXISTS idx_oracle_snapshots_market_id;
DROP INDEX IF EXISTS idx_creator_confirmations_belief_id;
DROP INDEX IF EXISTS idx_creator_profiles_wallet_address;
DROP INDEX IF EXISTS idx_market_settlements_market_id;
DROP INDEX IF EXISTS idx_market_resolutions_market_id;
DROP INDEX IF EXISTS idx_market_events_tx_hash;
DROP INDEX IF EXISTS idx_market_events_market_id;
DROP INDEX IF EXISTS idx_market_positions_tx_hash;
DROP INDEX IF EXISTS idx_market_positions_wallet_address;
DROP INDEX IF EXISTS idx_market_positions_market_id;
DROP INDEX IF EXISTS idx_markets_category;
DROP INDEX IF EXISTS idx_markets_status;
DROP INDEX IF EXISTS idx_markets_contract_market_id;
DROP INDEX IF EXISTS idx_markets_contract_address;
DROP INDEX IF EXISTS idx_markets_chain_id;
DROP INDEX IF EXISTS idx_markets_belief_id;
DROP INDEX IF EXISTS idx_belief_sources_belief_id;
DROP INDEX IF EXISTS idx_beliefs_author;
DROP INDEX IF EXISTS idx_beliefs_status;
DROP INDEX IF EXISTS idx_users_wallet_address;

DROP TABLE IF EXISTS oracle_snapshots CASCADE;
DROP TABLE IF EXISTS creator_confirmations CASCADE;
DROP TABLE IF EXISTS creator_profiles CASCADE;
DROP TABLE IF EXISTS market_settlements CASCADE;
DROP TABLE IF EXISTS market_resolutions CASCADE;
DROP TABLE IF EXISTS market_events CASCADE;
DROP TABLE IF EXISTS market_positions CASCADE;
DROP TABLE IF EXISTS markets CASCADE;
DROP TABLE IF EXISTS belief_sources CASCADE;
DROP TABLE IF EXISTS beliefs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
